-- select name, mark from student order by mark asc;
-- select avg(mark) as mark, department from student group by department;
-- select count(name) as count, department from student group by department order by count desc;
